[workspace]
members = ["riddle",
"riddle-audio",
"riddle-common",
"riddle-font",
"riddle-image",
"riddle-input",
"riddle-macros",
"riddle-math",
"riddle-platform-common",
"riddle-platform-winit",
"riddle-renderer-wgpu",
"riddle-time"]